import { escapeHTML } from '../core/consequence-identity.js';

// Module-owned control symbols. Need configurations use needIcon so custom art is preserved.
export const CONTROL_ART = Object.freeze({
  "fa-band-aid": "pain",
  "fa-bed": "exhaustion",
  "fa-brain": "sanity",
  "fa-cloud": "environmental",
  "fa-couch": "comfort",
  "fa-eye": "fear",
  "fa-moon": "fatigue",
  "fa-radiation": "radiation",
  "fa-smile": "morale",
  "fa-snowflake": "cold",
  "fa-sun": "heat",
  "fa-tint": "thirst",
  "fa-leaf": "environmental",
  "fa-align-left": "ui-align-left",
  "fa-arrow-down": "ui-arrow-down",
  "fa-arrow-up": "ui-arrow-up",
  "fa-arrows-alt-v": "ui-arrows-alt-v",
  "fa-balance-scale": "ui-balance-scale",
  "fa-bolt": "ui-bolt",
  "fa-bullhorn": "ui-bullhorn",
  "fa-campground": "ui-campground",
  "fa-chart-bar": "ui-chart-bar",
  "fa-chart-line": "ui-chart-line",
  "fa-check": "ui-check",
  "fa-check-circle": "ui-check-circle",
  "fa-check-square": "ui-check-square",
  "fa-chevron-down": "ui-chevron-down",
  "fa-chevron-right": "ui-chevron-right",
  "fa-chevron-up": "ui-chevron-up",
  "fa-circle-info": "ui-circle-info",
  "fa-clock": "ui-clock",
  "fa-code": "ui-code",
  "fa-cog": "ui-cog",
  "fa-comment-alt": "ui-comment-alt",
  "fa-compress-arrows-alt": "ui-compress-arrows-alt",
  "fa-crosshairs": "ui-crosshairs",
  "fa-download": "ui-download",
  "fa-eraser": "ui-eraser",
  "fa-exclamation-triangle": "ui-exclamation-triangle",
  "fa-triangle-exclamation": "ui-exclamation-triangle",
  "fa-eye-slash": "ui-eye-slash",
  "fa-feather-alt": "ui-feather-alt",
  "fa-file-code": "ui-file-code",
  "fa-file-export": "ui-file-export",
  "fa-file-import": "ui-file-import",
  "fa-filter": "ui-filter",
  "fa-fire": "ui-fire",
  "fa-heartbeat": "ui-heartbeat",
  "fa-history": "ui-history",
  "fa-hourglass-half": "ui-hourglass-half",
  "fa-hourglass-start": "ui-hourglass-start",
  "fa-link": "ui-link",
  "fa-list": "ui-list",
  "fa-lock": "ui-lock",
  "fa-magic": "ui-magic",
  "fa-minus": "ui-minus",
  "fa-mountain": "ui-mountain",
  "fa-pen": "ui-pen",
  "fa-pencil": "ui-pen",
  "fa-plus": "ui-plus",
  "fa-question": "ui-question",
  "fa-rocket": "ui-rocket",
  "fa-rotate": "ui-rotate",
  "fa-route": "ui-route",
  "fa-save": "ui-save",
  "fa-search": "ui-search",
  "fa-shield-alt": "ui-shield-alt",
  "fa-shoe-prints": "ui-shoe-prints",
  "fa-sign-in-alt": "ui-sign-in-alt",
  "fa-skull": "ui-skull",
  "fa-sliders-h": "ui-sliders-h",
  "fa-star": "ui-star",
  "fa-terminal": "ui-terminal",
  "fa-theater-masks": "ui-theater-masks",
  "fa-times": "ui-times",
  "fa-trash": "ui-trash",
  "fa-tv": "ui-tv",
  "fa-undo": "ui-undo",
  "fa-undo-alt": "ui-undo",
  "fa-upload": "ui-upload",
  "fa-user-plus": "ui-user-plus",
  "fa-user-secret": "ui-user-secret",
  "fa-users": "ui-users",
  "fa-users-slash": "ui-users-slash",
  "fa-utensils": "ui-utensils",
  "fa-wifi": "ui-wifi",
  "fa-window-restore": "ui-window-restore"
});

export function controlIconClass(icon) {
  const tokens = String(icon || '').trim().split(/\s+/);
  const symbol = tokens.find(token => Object.hasOwn(CONTROL_ART, token));
  if (symbol) return `mn-icon ${symbol}`;
  // Extension-provided controls can still supply a safe Font Awesome class.
  if (/^(?:(?:fa[srlbd]?|fa-[a-z0-9-]+)\s*)+$/.test(String(icon))) return `fas ${icon}`;
  return 'mn-icon fa-question';
}

export function controlIcon(icon, className = '') {
  return `<i class="${escapeHTML(controlIconClass(icon))}${className ? ` ${escapeHTML(className)}` : ''}" aria-hidden="true"></i>`;
}
